"""add new field for user

Revision ID: 70566532b26a
Revises: 18b35d4617ad
Create Date: 2026-06-04 10:48:36.677209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "70566532b26a"
down_revision: Union[str, Sequence[str], None] = "18b35d4617ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=64), nullable=False))
    op.add_column("users", sa.Column("surname", sa.String(length=64), nullable=False))
    op.add_column("users", sa.Column("username", sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.drop_column("users", "surname")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
