"""add rename field

Revision ID: 7eeec6300c00
Revises: 70566532b26a
Create Date: 2026-06-04 10:49:26.786078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7eeec6300c00"
down_revision: Union[str, Sequence[str], None] = "70566532b26a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("patronymics", sa.String(length=64), nullable=False)
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "patronymics")
    # ### end Alembic commands ###
